name: My First Action

on: [push]

jobs:
  say-hello:
     runs-on: ubuntu-latest
     steps:
       - name: Print Welcome Message
         run: echo "Hello Kubeflow! My Environment is officially ready"